### ISSUE TITLE
2.5.12 where

### ISSUE THREAD

**Issue by mix127** [meshtastic/meshtastic.github.io#3]
Where is heltec v2_1 ?
I use it in 2.5.5

**Comment by garthvh** [comment]
It has not been officially supported for more than a year

**Comment by mix127** [comment]
So what should I do, throw away the equipment for more than 100zł ? 

It's worse than closed source. Open source should support hardware and not abandon it like greedy companies. I don't know why I would use a meshtastic network when it is no different from commercial software.
